import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/context/AuthProvider';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';
import ThemeProvider from '@/context/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: {
		default: 'AnonText',
		template: '%s | AnonText',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<html lang='en'>
				<body className={`${inter.className} min-h-screen flex flex-col dark:bg-gray-950 overflow-hidden overflow-y-scroll`}>
					<ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
						<Navbar />
						<div className='flex-1 flex flex-col container max-w-screen-md lg:max-w-screen-lg 2xl:max-w-screen-xl mx-auto '>
							{children}
						</div>
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</AuthProvider>
	);
}
